import { ChartOptions } from './buy-sell.model';

const Market = [
  {
      img: 'assets/images/svg/crypto-icons/btc.svg',
      coinName: "Bitcoin (BTC)",
      price: "$47,071.60",
      pairs: "BTC/USD",
      high: "$28,722.76",
      low: "$68,789.63",
      marketVolume: "$888,411,910",
      percentage: "1.50%",
      icon: "mdi mdi-trending-up",
      iconClass: "success",
  },
  {
      img: 'assets/images/svg/crypto-icons/eth.svg',
      coinName: "Ethereum (ETH)",
      price: "$3,813.14",
      pairs: "ETH/USDT",
      high: "$4,036.24",
      low: "$3,588.14",
      marketVolume: "$314,520,675",
      percentage: "0.42%",
      icon: "mdi mdi-trending-down",
      iconClass: "danger",
  },
  {
      img: 'assets/images/svg/crypto-icons/ltc.svg',
      coinName: "Litecoin (LTC)",
      price: "$149.65",
      pairs: "LTC/USDT",
      high: "$412.96",
      low: "$104.33",
      marketVolume: "$314,520,675",
      percentage: "0.89%",
      icon: "mdi mdi-trending-up",
      iconClass: "success",
  },
  {
      img: 'assets/images/svg/crypto-icons/ltc.svg',
      coinName: "Monero (XMR)",
      price: "$17,491.16",
      pairs: "XRM/USDT",
      high: "$31,578.35",
      low: "$8691.75",
      marketVolume: "$9,847,327",
      percentage: "1.92%",
      icon: "mdi mdi-trending-up",
      iconClass: "success",
  },
  {
      img: 'assets/images/svg/crypto-icons/sol.svg',
      coinName: "Solana (SOL)",
      price: "$172.93",
      pairs: "SOL/USD",
      high: "$178.37",
      low: "$172.3",
      marketVolume: "$40,559,274",
      percentage: "2.87%",
      icon: "mdi mdi-trending-down",
      iconClass: "danger",
  },
  {
      img: 'assets/images/svg/crypto-icons/ant.svg',
      coinName: "Aragon (ANT)",
      price: "$13.31",
      pairs: "ANT/USD",
      high: "$13.85",
      low: "$12.53",
      marketVolume: "$156,209,195.18",
      percentage: "3.96%",
      icon: "mdi mdi-trending-up",
      iconClass: "success",
  },
  {
      img: 'assets/images/svg/crypto-icons/fil.svg',
      coinName: "Filecoin (FIL)",
      price: "$35.21",
      pairs: "FIL/USD",
      high: "$36.41",
      low: "$35.03",
      marketVolume: "$374,618,945.51",
      percentage: "0.84%",
      icon: "mdi mdi-trending-down",
      iconClass: "danger",
  },
  {
      img: 'assets/images/svg/crypto-icons/aave.svg',
      coinName: "Aave (AAVE)",
      price: "$275.47",
      pairs: "AAVE/USDT",
      high: "$277.11",
      low: "$255.01",
      marketVolume: "$156,209,195.18",
      percentage: "8.20%",
      icon: "mdi mdi-trending-up",
      iconClass: "success",
  },
  {
      img: 'assets/images/svg/crypto-icons/ada.svg',
      coinName: "Cardano (ADA)",
      price: "$1.35",
      pairs: "ADA/USD",
      high: "$1.39",
      low: "$1.32",
      marketVolume: "$880,387,980.14",
      percentage: "0.42%",
      icon: "mdi mdi-trending-down",
      iconClass: "danger",
  },
  {
      img: 'assets/images/svg/crypto-icons/dot.svg',
      coinName: "Polkadot (DOT)",
      price: "$28.88",
      pairs: "DOT/USD",
      high: "$30.56",
      low: "$28.66",
      marketVolume: "$880,387,980.14",
      percentage: "1.03%",
      icon: "mdi mdi-trending-up",
      iconClass: "success",
  },
];

export { Market };
