const Transactions = [
    {
        icon:"ri-arrow-right-up-fill",
        bg_color: "danger",
        date: "24 Dec, 2021",
        time: "08:58AM",
        image: "assets/images/svg/crypto-icons/btc.svg",
        currency: "BTC",
        from: "Wallet",
        to: "Thomas Taylor",
        details: "Membership Fees",
        id: "16b1d9234b61e8778d9e3588f20",
        type: "Withdraw",
        amount: "-142.35 BTC",
        amount1: "$697.88k",
        status: "Processing",
        status_color: 'warning',
        isSelected:false
    },
    {
        icon:"ri-arrow-right-down-fill",
        bg_color: "success ",
        date: "16 Dec, 2021",
        time: "10:58AM",
        image: "assets/images/svg/crypto-icons/eth.svg",
        currency: "ETH",
        from: "Tonya Noble",
        to: "Wallet",
        details: "Spring Telephone Network",
        id: "0a4b5e0e15d70ce79809eabbe",
        type: "Deposit",
        amount: "+342.35 ETH",
        amount1: "$14565.35",
        status: "Success",
        status_color: 'success',
        isSelected:false
    },
    {
        icon:"ri-arrow-right-down-fill",
        bg_color: "success ",
        date: "04 Jan, 2021",
        time: "10:58AM",
        image: "assets/images/svg/crypto-icons/eur.svg",
        currency: "EUR",
        from: "Nancy Martino",
        to: "Wallet",
        details: "Funding Purse with Payment Check",
        id: "cca3da2b7711985361825f615e9",
        type: "Deposit",
        amount: "+174.23 EUR",
        amount1: "$354.14",
        status: "Failed",
        status_color: 'danger',
        isSelected:false
    },
     {
        icon:"ri-arrow-right-up-fill",
        bg_color: "danger",
        date: "28 Oct, 2021",
        time: "11:42AM",
        image: "assets/images/svg/crypto-icons/gbp.svg",
        currency: "GBP",
        from: "Wallet",
        to: "Michael Morris",
        details: "British Pound Sterling Block",
        id: "062e0e0123f2b1e9862f659c28",
        type: "Withdraw",
        amount: "-365.00 GBP",
        amount1: "$7532.21",
        status: "Success",
        status_color: 'success',
        isSelected:false
    },
     {
        icon:"ri-arrow-right-down-fill",
        bg_color: "success ",
        date: "14 Nov, 2021",
        time: "12:38PM",
        image: "assets/images/svg/crypto-icons/jpy.svg",
        currency: "JPY",
        from: "Alexis Clarke",
        to: "Wallet",
        details: "Platinum Business",
        id: "1deffa9713917ee0af26bbb5f272",
        type: "Deposit",
        amount: "+341.74 JPY",
        amount1: "$748.10",
        status: "Processing",
        status_color: 'warning',
        isSelected:false
    },
     {
        icon:"ri-arrow-right-up-fill",
        bg_color: "danger",
        date: "02 Jan, 2021",
        time: "08:58AM",
        image: "assets/images/svg/crypto-icons/xrp.svg",
        currency: "XRP",
        from: "Wallet",
        to: "Kevin Dawson",
        details: "Business Advantage Fundaments - Banking",
        id: "186aa96d8014061d994f025ac4",
        type: "Withdraw",
        amount: "-240.74 XRP",
        amount1: "$3254.20",
        status: "Failed",
        status_color: 'danger',
        isSelected:false
    },
     {
        icon:"ri-arrow-right-down-fill",
        bg_color: "success ",
        date: "17 Oct, 2021",
        time: "07:08PM",
        image: "assets/images/svg/crypto-icons/ltc.svg",
        currency: "LTC",
        from: "Tonya Noble",
        to: "Wallet",
        details: "Litecoin Sale",
        id: "c94b5581418c41c2c74448a5ec",
        type: "Deposit",
        amount: "+298.72 LTC",
        amount1: "$149.32",
        status: "Success",
        status_color: 'success',
        isSelected:false
    },
    {
        icon:"ri-arrow-right-up-fill",
        bg_color: "danger",
        date: "27 Dec, 2021",
        time: "01:24PM",
        image: "assets/images/svg/crypto-icons/xmr.svg",
        currency: "XMR",
        from: "Wallet",
        to: "Mary Cousar",
        details: "Monero Purchase",
        id: "9a592451d1b0e0e5af6d4908f7",
        type: "Withdraw",
        amount: "-365.13 XMR",
        amount1: "$754.91",
        status: "Failed",
        status_color: 'danger',
        isSelected:false
    },
    {
        icon:"ri-arrow-right-down-fill",
        bg_color: "success ",
        date: "23 Dec, 2021",
        time: "01:47AM",
        image: "assets/images/svg/crypto-icons/xpm.svg",
        currency: "XPM",
        from: "Glen Matney",
        to: "Wallet",
        details: "British Pound Sterling Block",
        id: "c1bf44fd100fff59a5c64c28dfe0",
        type: "Deposit",
        amount: "+174.09 XPM",
        amount1: "$657.28",
        status: "Processing",
        status_color: 'warning',
        isSelected:false
    },
    {
        icon:"ri-arrow-right-down-fill",
        bg_color: "success ",
        date: "15 Dec, 2021",
        time: "08:58AM",
        image: "assets/images/svg/crypto-icons/ppt.svg",
        currency: "PPT",
        from: "Timothy Smith",
        to: "Wallet",
        details: "British Pound Sterling Block",
        id: "v98p141d5f4j145614sdsa78gh48t98",
        type: "Withdraw",
        amount: "-142.35 PPT",
        amount1: "$398.35",
        status: "Success",
        status_color: 'success',
        isSelected:false
    },
  ];

export{ Transactions };
