// Related Job
const related = [
    {
        id: '1',
        logo: 'assets/images/companies/img-1.png',
        title: 'Web designer',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Freelance', 'Urgent'],
        location: 'Escondido,California',
        date: '3 min ago',
    },
    {
        id: '2',
        logo: 'assets/images/companies/img-2.png',
        title: 'Marketing Director',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Part Time', 'Freelance'],
        location: 'Stordorf, Germany',
        date: '30 min ago',
    },
    {
        id: '3',
        logo: 'assets/images/companies/img-3.png',
        title: 'Product Sales Specialist',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Private'],
        location: 'Cullera, Spain',
        date: '2 days ago',
    },
    {
        id: '4',
        logo: 'assets/images/companies/img-1.png',
        title: 'Web designer',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Freelance', 'Urgent'],
        location: 'Escondido,California',
        date: '3 min ago',
    },
    {
        id: '5',
        logo: 'assets/images/companies/img-2.png',
        title: 'Marketing Director',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Part Time', 'Freelance'],
        location: 'Stordorf, Germany',
        date: '30 min ago',
    },
    {
        id: '6',
        logo: 'assets/images/companies/img-3.png',
        title: 'Product Sales Specialist',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Private'],
        location: 'Cullera, Spain',
        date: '2 days ago',
    }
]

export { related }