const Orders = [
  {
      date: "2022-07-04",
      time: "03:45PM",
      img: 'assets/images/svg/crypto-icons/btc.svg',
      coinName: "Bitcoin (BTC)",
      type: "Buy",
      typeClass: "success",
      quantity: "08",
      orderValue: "$3,70,683.2",
      avgPrice: "$46,154.30",
      price: "$46,335.40",
      status: "Successful",
      statusClass: "success",
  },
  {
      date: "2022-07-04",
      time: "02:47PM",
      img: 'assets/images/svg/crypto-icons/eth.svg',
      coinName: "Ethereum (ETH)",
      type: "Sell",
      typeClass: "danger",
      quantity: "50",
      orderValue: "$1,87,433",
      avgPrice: "$3,744.48",
      price: "$3,748.66",
      status: "Cancelled",
      statusClass: "danger",
  },
  {
      date: "2022-07-04",
      time: "10:24AM",
      img: 'assets/images/svg/crypto-icons/xmr.svg',
      coinName: "Monero (XMR)",
      type: "Sell",
      typeClass: "danger",
      quantity: "150",
      orderValue: "$33,982.5",
      avgPrice: "$227.30",
      price: "$226.55",
      status: "Successful",
      statusClass: "success",
  },
  {
      date: "2022-07-04",
      time: "11:20AM",
      img: 'assets/images/svg/crypto-icons/mkr.svg',
      coinName: "Maker (MKR)",
      type: "Buy",
      typeClass: "success",
      quantity: "60",
      orderValue: "$1,43,445",
      avgPrice: "$2,470.30",
      price: "$2,390.75",
      status: "Pending",
      statusClass: "warning",
  },
  {
      date: "2022-07-04",
      time: "02:47PM",
      img: 'assets/images/svg/crypto-icons/yfi.svg',
      coinName: "Yearn.finance (YFI)",
      type: "Buy",
      typeClass: "success",
      quantity: "25",
      orderValue: "$9,81,906",
      avgPrice: "$37,632.17",
      price: "$39,276.24",
      status: "Cancelled",
      statusClass: "danger",
  },
  {
      date: "2022-07-08",
      time: "09:20AM",
      img: 'assets/images/svg/crypto-icons/mkr.svg',
      coinName: "Maker (MKR)",
      type: "Sell",
      typeClass: "danger",
      quantity: "20",
      orderValue: "$50,243",
      avgPrice: "$2,324.65",
      price: "$2,512.15",
      status: "Successful",
      statusClass: "success",
  },
  {
      date: "2022-07-04",
      time: "11:42AM",
      img: 'assets/images/svg/crypto-icons/xmr.svg',
      coinName: "Litecoin (LTC)",
      type: "Buy",
      typeClass: "success",
      quantity: "200",
      orderValue: "$29,500",
      avgPrice: "$144.00",
      price: "$147.50",
      status: "Pending",
      statusClass: "warning",
  },
  {
      date: "2022-07-06",
      time: "03:36PM",
      img: 'assets/images/svg/crypto-icons/dash.svg',
      coinName: "Monero (XMR)",
      type: "Sell",
      typeClass: "danger",
      quantity: "75",
      orderValue: "$17,874",
      avgPrice: "$221.61",
      price: "$238.32",
      status: "Successful",
      statusClass: "success",
  },
  {
      date: "2022-07-05",
      time: "03:36PM",
      img: 'assets/images/svg/crypto-icons/neo.svg',
      coinName: "Dash (DASH)",
      type: "Buy",
      typeClass: "success",
      quantity: "45",
      orderValue: "$14,962.5",
      avgPrice: "$147.39",
      price: "$142.5",
      status: "Cancelled",
      statusClass: "danger",
  },
  {
      date: "2022-07-01",
      time: "03:36PM",
      img: 'assets/images/svg/crypto-icons/neo.svg',
      coinName: "Neo (NEO)",
      type: "Sell",
      typeClass: "danger",
      quantity: "36",
      orderValue: "$77,232.24",
      avgPrice: "$2,274.21",
      price: "$2,145.34",
      status: "Pending",
      statusClass: "warning",
  },
  {
      date: "2022-07-02",
      time: "11:45AM",
      img: 'assets/images/svg/crypto-icons/mln.svg',
      coinName: "Enzyme (MLN)",
      type: "Sell",
      typeClass: "danger",
      quantity: "68",
      orderValue: "$6,296.8",
      avgPrice: "$94.21",
      price: "$92.60",
      status: "Successful",
      statusClass: "success",
  },
  {
      date: "2022-07-03",
      time: "02:32AM",
      img: 'assets/images/svg/crypto-icons/eth.svg',
      coinName: "Ethereum (ETH)",
      type: "Buy",
      typeClass: "success",
      quantity: "72",
      orderValue: "$2,69,602.56",
      avgPrice: "$3,744.48",
      price: "$3,748.66",
      status: "Cancelled",
      statusClass: "danger",
  },
];

export { Orders };
