// Job Grid
const jobgrid = [
    {
        id: '0',
        logo: '',
        title: '',
        companyname: '',
        content: "",
        type: [],
        location: '',
        date: '',
    },
    {
        id: '1',
        logo: 'assets/images/companies/img-1.png',
        title: 'Education Training',
        companyname: 'Micro Design',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Freelance', 'Urgent'],
        location: 'Escondido,California',
        date: '15 Sep, 2022',
    },
    {
        id: '2',
        logo: 'assets/images/companies/img-2.png',
        title: 'Magento Developer',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Part Time', 'Freelance'],
        location: 'Stordorf, Germany',
        date: '15 Sep, 2022',
    },
    {
        id: '3',
        logo: 'assets/images/companies/img-3.png',
        title: 'Product Designer',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Private'],
        location: 'Cullera, Spain',
        date: '14 Sep, 2022',
    },
    {
        id: '4',
        logo: 'assets/images/companies/img-5.png',
        title: 'React Developer',
        companyname: 'iTest Factory',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Freelance', 'Urgent'],
        location: 'Haren, Germany',
        date: '13 Sep, 2022',
    },
    {
        id: '5',
        logo: 'assets/images/companies/img-6.png',
        title: 'UI/UX designer',
        companyname: 'Creative Team',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Part Time'],
        location: 'inninga, Sweden',
        date: '13 Sep, 2022',
    },
    {
        id: '6',
        logo: 'assets/images/companies/img-7.png',
        title: 'Marketing Director',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Freelance', 'Urgent'],
        location: 'Zhoukou, China',
        date: '12 Sep, 2022',
    },
    {
        id: '7',
        logo: 'assets/images/companies/img-8.png',
        title: 'Full Stack Engineer',
        companyname: 'Syntyce Solutions',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time'],
        location: 'Boroaia, Romania',
        date: '11 Sep, 2022',
    },
    {
        id: '8',
        logo: 'assets/images/companies/img-2.png',
        title: 'HTML Developer',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Part Time', 'Freelance'],
        location: 'Donsieders, Germany',
        date: '10 Sep, 2022',
    },
    {
        id: '9',
        logo: 'assets/images/companies/img-3.png',
        title: 'Business Associate',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Freelance', 'Urgent'],
        location: 'Sermerieu, France',
        date: '09 Sep, 2022',
    },
    {
        id: '10',
        logo: 'assets/images/companies/img-5.png',
        title: 'Assistant / Store Keeper',
        companyname: 'Force Medicines',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Part Time'],
        location: 'San Lorenzo, Philippines',
        date: '08 Sep, 2022',
    },
    {
        id: '11',
        logo: 'assets/images/companies/img-6.png',
        title: 'Product Sales Specialist',
        companyname: 'Themesbrand',
        content: "As a Product Designer, you will work within a Product Delivery Team fused with UX,engineering, product and data talent.",
        type: ['Full Time', 'Private'],
        location: 'Pazmand, Hungary',
        date: '08 Sep, 2022',
    }
]

export { jobgrid }