const exploreData = [
  {
    id: 1,
    img: 'assets/images/nft/gif/img-3.gif',
    likes: "37.41",
    title: "Walking On Air",
    category: "Artwork",
    type:"gif",
    sale_type:"On Auction",
    highestBid: "10.35",
    price: "14.617",
    isIcon: true,
},
{
    id: 2,
    img: 'assets/images/nft/img-03.jpg',
    likes: "19.29",
    title: "Creative Filtered Portrait",
    category: "Photography",
    type:"jpg",
    sale_type:"Has Offers",
    highestBid: "75.3",
    price: "67.36",
},
{
    id: 3,
    img: 'assets/images/nft/img-02.jpg',
    likes: "23.63",
    title: "The Chirstoper",
    category: "Music",
    type:"jpg",
    sale_type:"On Auction",
    highestBid: "412.30",
    price: "394.7",
    isIcon: true,
},
{
    id: 4,
    img: 'assets/images/nft/gif/img-4.gif',
    likes: "15.93",
    title: "Evolved Reality",
    category: "Video",
    type:"gif",
    sale_type:"On Auction",
    highestBid: "2.75",
    price: "3.167",
},
{
    id: 5,
    img: 'assets/images/nft/img-01.jpg',
    likes: "14.85",
    title: "Abstract Face Painting",
    category: "Collectibles",
    type:"jpg",
    sale_type:"On Auction",
    highestBid: "122.34",
    price: "97.8",
},
{
    id: 6,
    img: 'assets/images/nft/img-05.jpg',
    likes: "64.10",
    title: "Long-tailed Macaque",
    category: "Artwork",
    type:"jpg",
    sale_type:"Has Offers",
    highestBid: "874.01",
    price: "745.14",
    isIcon: true,
},
{
    id: 7,
    img: 'assets/images/nft/img-06.jpg',
    likes: "36.42",
    title: "Robotic Body Art",
    category: "Artwork",
    type:"jpg",
    sale_type:"Has Offers",
    highestBid: "41.65",
    price: "34.81",
    isIcon: true,
},
{
    id: 8,
    img: 'assets/images/nft/gif/img-2.gif',
    likes: "94.1",
    title: "Trendy Fashion Portraits",
    category: "3d Style",
    type:"gif",
    sale_type:"Has Offers",
    highestBid: "674.92",
    price: "563.81",
},
{
    id: 9,
    img: 'assets/images/nft/img-04.jpg',
    likes: "34.12",
    title: "Smillevers Crypto",
    category: "Crypto Card",
    type:"jpg",
    sale_type:"On Auction",
    highestBid: "41.658",
    price: "34.81",
    isIcon: true,
},
{
    id: 10,
    img: 'assets/images/nft/gif/img-1.gif',
    likes: "8.42",
    title: "Patterns Arts & Culture",
    category: "Artwork",
    type:"gif",
    sale_type:"On Auction",
    highestBid: "9.64",
    price: "14.167",
},
{
    id: 11,
    img: 'assets/images/nft/img-03.jpg',
    likes: "19.29",
    title: "Creative Filtered Portrait",
    category: "Video",
    type:"jpg",
    sale_type:"On Auction",
    highestBid: "75.3",
    price: "267.36",
},
{
    id: 12,
    img: 'assets/images/nft/gif/img-4.gif',
    likes: "15.93",
    title: "Evolved Reality",
    category: "Games",
    type:"gif",
    sale_type:"On Auction",
    highestBid: "2.75",
    price: "324.26",
},
{
    id: 13,
    img: 'assets/images/nft/img-01.jpg',
    likes: "14.85",
    title: "Abstract Face Painting",
    category: "Photography",
    type:"jpg",
    sale_type:"On Auction",
    highestBid: "122.34",
    price: "245.8",
},
{
    id: 14,
    img: 'assets/images/nft/img-05.jpg',
    likes: "64.10",
    title: "Long-tailed Macaque",
    category: "Collectibles",
    type:"mp4",
    sale_type:"On Auction",
    highestBid: "874.01",
    price: "340.14",
},
{
    id: 15,
    img: 'assets/images/nft/img-06.jpg',
    likes: "36.42",
    title: "Robotic Body Art",
    category: "Photography",
    type:"mp3",
    sale_type:"Has Offers",
    highestBid: "121.81",
    price: "41.658",
},
];

export { exploreData };
